###
GET http://localhost:3000/fibonacci/0

###
GET http://localhost:3000/fibonacci/1

###
GET http://localhost:3000/fibonacci/2

###
GET http://localhost:3000/fibonacci/3

###
GET http://localhost:3000/fibonacci/4

###
GET http://localhost:3000/fibonacci/40

###
GET http://localhost:3001/fibonacci/42
